#include "RNOH/PackageProvider.h"
#include "generated/RNOHGeneratedPackage.h"
// #include "ViewPagerPackage.h"
//#include "GestureHandlerPackage.h"
//#include "ReanimatedPackage.h"
//#include "ViewPagerPackage.h"

using namespace rnoh;

std::vector<std::shared_ptr<Package>> PackageProvider::getPackages(
    Package::Context ctx) {
  return {
      std::make_shared<RNOHGeneratedPackage>(ctx), // generated by codegen v1
//         std::make_shared<ViewPagerPackage>(ctx)
//        std::make_shared<GestureHandlerPackage>(ctx),
//        std::make_shared<ViewPagerPackage>(ctx),
//        std::make_shared<ReanimatedPackage>(ctx)
  };
}